class HomeLocators:
    HOME_LINK_ROLE = "link"
    HOME_LINK_NAME = "Home"
    PRODUCTS_LINK_NAME = "Products"
    CART_LINK_NAME = "Cart"
    SIGNUP_LOGIN_LINK_NAME = "Signup / Login"
    TEST_CASES_LINK_NAME = "Test Cases"
    CONTACT_US_LINK_NAME = "Contact us"
    SUBSCRIPTION_TEXT = "SUBSCRIPTION"
    SUBSCRIPTION_EMAIL_PLACEHOLDER = "Your email address"
    SUBSCRIPTION_SUCCESS_MESSAGE = "You have been successfully subscribed!"
    HERO_TEXT = "Full-Fledged practice website for Automation Engineers"
    RECOMMENDED_ITEMS_TEXT = "RECOMMENDED ITEMS"
    CATEGORY_TEXT = "CATEGORY"
    WOMEN_TEXT = "Women"
    MEN_TEXT = "Men"
    SCROLL_TOP_LINK_NAME = ""
