class CheckoutLocators:
    ADDRESS_DETAILS_TEXT = "Address Details"
    REVIEW_ORDER_TEXT = "Review Your Order"
    PLACE_ORDER_TEXT = "Place Order"
    ORDER_PLACED_TEXT = "ORDER PLACED!"
    ORDER_SUCCESS_TEXT = "Congratulations! Your order has been confirmed!"
    DOWNLOAD_INVOICE_TEXT = "Download Invoice"
    CONTINUE_BUTTON_TEXT = "Continue"
    COMMENT_BOX_NAME = "message"
    NAME_ON_CARD_TEST_ID = "name-on-card"
    CARD_NUMBER_TEST_ID = "card-number"
    CVC_TEST_ID = "cvc"
    EXPIRY_MONTH_TEST_ID = "expiry-month"
    EXPIRY_YEAR_TEST_ID = "expiry-year"
    PAY_CONFIRM_TEXT = "Pay and Confirm Order"
