class ProductsLocators:
    PRODUCTS_HEADING = "ALL PRODUCTS"
    SEARCHED_PRODUCTS_TEXT = "SEARCHED PRODUCTS"
    VIEW_PRODUCT_LINK_NAME = "View Product"
    ADD_TO_CART_TEXT = "Add to cart"
    CONTINUE_SHOPPING_BUTTON_NAME = "Continue Shopping"
    VIEW_CART_LINK_NAME = "View Cart"
    SEARCH_INPUT_PLACEHOLDER = "Search Product"
    SEARCH_BUTTON_ROLE = "button"
    SEARCH_BUTTON_NAME = "Submit Search"
    WRITE_REVIEW_TEXT = "WRITE YOUR REVIEW"
    REVIEW_SUCCESS_MESSAGE = "Thank you for your review."
    NAME_PLACEHOLDER = "Your Name"
    EMAIL_PLACEHOLDER = "Email Address"
    REVIEW_PLACEHOLDER = "Add Review Here!"
